USE [master]
GO

/****** Object:  Database [VitualTFS]    Script Date: 03/23/2013 15:37:26 ******/
CREATE DATABASE [VitualTFS] ON  PRIMARY 
( NAME = N'VitualTFS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\VitualTFS.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'VitualTFS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\VitualTFS_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [VitualTFS] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VitualTFS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [VitualTFS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [VitualTFS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [VitualTFS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [VitualTFS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [VitualTFS] SET ARITHABORT OFF 
GO

ALTER DATABASE [VitualTFS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [VitualTFS] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [VitualTFS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [VitualTFS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [VitualTFS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [VitualTFS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [VitualTFS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [VitualTFS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [VitualTFS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [VitualTFS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [VitualTFS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [VitualTFS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [VitualTFS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [VitualTFS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [VitualTFS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [VitualTFS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [VitualTFS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [VitualTFS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [VitualTFS] SET  READ_WRITE 
GO

ALTER DATABASE [VitualTFS] SET RECOVERY FULL 
GO

ALTER DATABASE [VitualTFS] SET  MULTI_USER 
GO

ALTER DATABASE [VitualTFS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [VitualTFS] SET DB_CHAINING OFF 
GO

