//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Models
{
    /// <summary>
    /// Model for table Area 
    /// </summary>
    public partial class AreaModel 
    {
        #region Ctor

        // Default contructor
        public AreaModel()
        {
            this.IsNewItem = true;
            this._area = new Area();
        }

        // Default contructor that set entity to field
        public AreaModel(Area area)
        {
        	this._area = area;
            this._id = area.Id;
            this._name_area = area.NameArea;
            this._originalArea = area.DeepClone();
        }

        #endregion


        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private Area _area;
        private Area _originalArea;
        
        public Area MapArea()
        {
            this._area.Id = this._id;
            this._area.NameArea = this._name_area;
        	return _area;
        }
        
        public void Undo()
        {
            if(this._originalArea == null) return;
            this._id = this._originalArea.Id;
            this._name_area = this._originalArea.NameArea;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalArea == null) return;
            this._area.Id = this._originalArea.Id;
            this._area.NameArea = this._originalArea.NameArea;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion


        #region Primitive Properties

        
        private System.Guid _id;
        public System.Guid Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                }
            }
        }
        
        private string _name_area;
        public string NameArea
        {
            get { return this._name_area; }
            set
            {
                if (this._name_area != value)
                {
                    this.IsDirty = true;
                    this._name_area = value;
                }
            }
        }

        #endregion


        #region all the custom code


        #endregion
    }
}
