//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Models
{
    /// <summary>
    /// Model for table aspnet_Profile 
    /// </summary>
    public partial class aspnet_ProfileModel 
    {
        #region Ctor

        // Default contructor
        public aspnet_ProfileModel()
        {
            this.IsNewItem = true;
            this._aspnet___profile = new aspnet_Profile();
        }

        // Default contructor that set entity to field
        public aspnet_ProfileModel(aspnet_Profile aspnet_profile)
        {
        	this._aspnet___profile = aspnet_profile;
            this._user_id = aspnet_profile.UserId;
            this._property_names = aspnet_profile.PropertyNames;
            this._property_values_string = aspnet_profile.PropertyValuesString;
            this._property_values_binary = aspnet_profile.PropertyValuesBinary;
            this._last_updated_date = aspnet_profile.LastUpdatedDate;
            this._originalaspnet_Profile = aspnet_profile.DeepClone();
        }

        #endregion


        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private aspnet_Profile _aspnet___profile;
        private aspnet_Profile _originalaspnet_Profile;
        
        public aspnet_Profile Mapaspnet_Profile()
        {
            this._aspnet___profile.UserId = this._user_id;
            this._aspnet___profile.PropertyNames = this._property_names;
            this._aspnet___profile.PropertyValuesString = this._property_values_string;
            this._aspnet___profile.PropertyValuesBinary = this._property_values_binary;
            this._aspnet___profile.LastUpdatedDate = this._last_updated_date;
        	return _aspnet___profile;
        }
        
        public void Undo()
        {
            if(this._originalaspnet_Profile == null) return;
            this._user_id = this._originalaspnet_Profile.UserId;
            this._property_names = this._originalaspnet_Profile.PropertyNames;
            this._property_values_string = this._originalaspnet_Profile.PropertyValuesString;
            this._property_values_binary = this._originalaspnet_Profile.PropertyValuesBinary;
            this._last_updated_date = this._originalaspnet_Profile.LastUpdatedDate;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalaspnet_Profile == null) return;
            this._aspnet___profile.UserId = this._originalaspnet_Profile.UserId;
            this._aspnet___profile.PropertyNames = this._originalaspnet_Profile.PropertyNames;
            this._aspnet___profile.PropertyValuesString = this._originalaspnet_Profile.PropertyValuesString;
            this._aspnet___profile.PropertyValuesBinary = this._originalaspnet_Profile.PropertyValuesBinary;
            this._aspnet___profile.LastUpdatedDate = this._originalaspnet_Profile.LastUpdatedDate;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion


        #region Primitive Properties

        
        private System.Guid _user_id;
        public System.Guid UserId
        {
            get { return this._user_id; }
            set
            {
                if (this._user_id != value)
                {
                    this.IsDirty = true;
                    this._user_id = value;
                }
            }
        }
        
        private string _property_names;
        public string PropertyNames
        {
            get { return this._property_names; }
            set
            {
                if (this._property_names != value)
                {
                    this.IsDirty = true;
                    this._property_names = value;
                }
            }
        }
        
        private string _property_values_string;
        public string PropertyValuesString
        {
            get { return this._property_values_string; }
            set
            {
                if (this._property_values_string != value)
                {
                    this.IsDirty = true;
                    this._property_values_string = value;
                }
            }
        }
        
        private byte[] _property_values_binary;
        public byte[] PropertyValuesBinary
        {
            get { return this._property_values_binary; }
            set
            {
                if (this._property_values_binary != value)
                {
                    this.IsDirty = true;
                    this._property_values_binary = value;
                }
            }
        }
        
        private System.DateTime _last_updated_date;
        public System.DateTime LastUpdatedDate
        {
            get { return this._last_updated_date; }
            set
            {
                if (this._last_updated_date != value)
                {
                    this.IsDirty = true;
                    this._last_updated_date = value;
                }
            }
        }

        #endregion


        #region all the custom code


        #endregion

    }
}
