//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Models
{
    /// <summary>
    /// Model for table aspnet_PersonalizationPerUser 
    /// </summary>
    public partial class aspnet_PersonalizationPerUserModel 
    {
        #region Ctor

        // Default contructor
        public aspnet_PersonalizationPerUserModel()
        {
            this.IsNewItem = true;
            this._aspnet___personalization_per_user = new aspnet_PersonalizationPerUser();
        }

        // Default contructor that set entity to field
        public aspnet_PersonalizationPerUserModel(aspnet_PersonalizationPerUser aspnet_personalizationperuser)
        {
        	this._aspnet___personalization_per_user = aspnet_personalizationperuser;
            this._id = aspnet_personalizationperuser.Id;
            this._path_id = aspnet_personalizationperuser.PathId;
            this._user_id = aspnet_personalizationperuser.UserId;
            this._page_settings = aspnet_personalizationperuser.PageSettings;
            this._last_updated_date = aspnet_personalizationperuser.LastUpdatedDate;
            this._originalaspnet_PersonalizationPerUser = aspnet_personalizationperuser.DeepClone();
        }

        #endregion


        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private aspnet_PersonalizationPerUser _aspnet___personalization_per_user;
        private aspnet_PersonalizationPerUser _originalaspnet_PersonalizationPerUser;
        
        public aspnet_PersonalizationPerUser Mapaspnet_PersonalizationPerUser()
        {
            this._aspnet___personalization_per_user.Id = this._id;
            this._aspnet___personalization_per_user.PathId = this._path_id;
            this._aspnet___personalization_per_user.UserId = this._user_id;
            this._aspnet___personalization_per_user.PageSettings = this._page_settings;
            this._aspnet___personalization_per_user.LastUpdatedDate = this._last_updated_date;
        	return _aspnet___personalization_per_user;
        }
        
        public void Undo()
        {
            if(this._originalaspnet_PersonalizationPerUser == null) return;
            this._id = this._originalaspnet_PersonalizationPerUser.Id;
            this._path_id = this._originalaspnet_PersonalizationPerUser.PathId;
            this._user_id = this._originalaspnet_PersonalizationPerUser.UserId;
            this._page_settings = this._originalaspnet_PersonalizationPerUser.PageSettings;
            this._last_updated_date = this._originalaspnet_PersonalizationPerUser.LastUpdatedDate;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalaspnet_PersonalizationPerUser == null) return;
            this._aspnet___personalization_per_user.Id = this._originalaspnet_PersonalizationPerUser.Id;
            this._aspnet___personalization_per_user.PathId = this._originalaspnet_PersonalizationPerUser.PathId;
            this._aspnet___personalization_per_user.UserId = this._originalaspnet_PersonalizationPerUser.UserId;
            this._aspnet___personalization_per_user.PageSettings = this._originalaspnet_PersonalizationPerUser.PageSettings;
            this._aspnet___personalization_per_user.LastUpdatedDate = this._originalaspnet_PersonalizationPerUser.LastUpdatedDate;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion


        #region Primitive Properties

        
        private System.Guid _id;
        public System.Guid Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                }
            }
        }
        
        private Nullable<System.Guid> _path_id;
        public Nullable<System.Guid> PathId
        {
            get { return this._path_id; }
            set
            {
                if (this._path_id != value)
                {
                    this.IsDirty = true;
                    this._path_id = value;
                }
            }
        }
        
        private Nullable<System.Guid> _user_id;
        public Nullable<System.Guid> UserId
        {
            get { return this._user_id; }
            set
            {
                if (this._user_id != value)
                {
                    this.IsDirty = true;
                    this._user_id = value;
                }
            }
        }
        
        private byte[] _page_settings;
        public byte[] PageSettings
        {
            get { return this._page_settings; }
            set
            {
                if (this._page_settings != value)
                {
                    this.IsDirty = true;
                    this._page_settings = value;
                }
            }
        }
        
        private System.DateTime _last_updated_date;
        public System.DateTime LastUpdatedDate
        {
            get { return this._last_updated_date; }
            set
            {
                if (this._last_updated_date != value)
                {
                    this.IsDirty = true;
                    this._last_updated_date = value;
                }
            }
        }

        #endregion


        #region all the custom code


        #endregion

    }
}
