//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Models
{
    /// <summary>
    /// Model for table aspnet_WebEvent_Events 
    /// </summary>
    public partial class aspnet_WebEvent_EventsModel 
    {
        #region Ctor

        // Default contructor
        public aspnet_WebEvent_EventsModel()
        {
            this.IsNewItem = true;
            this._aspnet___web_event___events = new aspnet_WebEvent_Events();
        }

        // Default contructor that set entity to field
        public aspnet_WebEvent_EventsModel(aspnet_WebEvent_Events aspnet_webevent_events)
        {
        	this._aspnet___web_event___events = aspnet_webevent_events;
            this._event_id = aspnet_webevent_events.EventId;
            this._event_time_utc = aspnet_webevent_events.EventTimeUtc;
            this._event_time = aspnet_webevent_events.EventTime;
            this._event_type = aspnet_webevent_events.EventType;
            this._event_sequence = aspnet_webevent_events.EventSequence;
            this._event_occurrence = aspnet_webevent_events.EventOccurrence;
            this._event_code = aspnet_webevent_events.EventCode;
            this._event_detail_code = aspnet_webevent_events.EventDetailCode;
            this._message = aspnet_webevent_events.Message;
            this._application_path = aspnet_webevent_events.ApplicationPath;
            this._application_virtual_path = aspnet_webevent_events.ApplicationVirtualPath;
            this._machine_name = aspnet_webevent_events.MachineName;
            this._request_url = aspnet_webevent_events.RequestUrl;
            this._exception_type = aspnet_webevent_events.ExceptionType;
            this._details = aspnet_webevent_events.Details;
            this._originalaspnet_WebEvent_Events = aspnet_webevent_events.DeepClone();
        }

        #endregion


        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private aspnet_WebEvent_Events _aspnet___web_event___events;
        private aspnet_WebEvent_Events _originalaspnet_WebEvent_Events;
        
        public aspnet_WebEvent_Events Mapaspnet_WebEvent_Events()
        {
            this._aspnet___web_event___events.EventId = this._event_id;
            this._aspnet___web_event___events.EventTimeUtc = this._event_time_utc;
            this._aspnet___web_event___events.EventTime = this._event_time;
            this._aspnet___web_event___events.EventType = this._event_type;
            this._aspnet___web_event___events.EventSequence = this._event_sequence;
            this._aspnet___web_event___events.EventOccurrence = this._event_occurrence;
            this._aspnet___web_event___events.EventCode = this._event_code;
            this._aspnet___web_event___events.EventDetailCode = this._event_detail_code;
            this._aspnet___web_event___events.Message = this._message;
            this._aspnet___web_event___events.ApplicationPath = this._application_path;
            this._aspnet___web_event___events.ApplicationVirtualPath = this._application_virtual_path;
            this._aspnet___web_event___events.MachineName = this._machine_name;
            this._aspnet___web_event___events.RequestUrl = this._request_url;
            this._aspnet___web_event___events.ExceptionType = this._exception_type;
            this._aspnet___web_event___events.Details = this._details;
        	return _aspnet___web_event___events;
        }
        
        public void Undo()
        {
            if(this._originalaspnet_WebEvent_Events == null) return;
            this._event_id = this._originalaspnet_WebEvent_Events.EventId;
            this._event_time_utc = this._originalaspnet_WebEvent_Events.EventTimeUtc;
            this._event_time = this._originalaspnet_WebEvent_Events.EventTime;
            this._event_type = this._originalaspnet_WebEvent_Events.EventType;
            this._event_sequence = this._originalaspnet_WebEvent_Events.EventSequence;
            this._event_occurrence = this._originalaspnet_WebEvent_Events.EventOccurrence;
            this._event_code = this._originalaspnet_WebEvent_Events.EventCode;
            this._event_detail_code = this._originalaspnet_WebEvent_Events.EventDetailCode;
            this._message = this._originalaspnet_WebEvent_Events.Message;
            this._application_path = this._originalaspnet_WebEvent_Events.ApplicationPath;
            this._application_virtual_path = this._originalaspnet_WebEvent_Events.ApplicationVirtualPath;
            this._machine_name = this._originalaspnet_WebEvent_Events.MachineName;
            this._request_url = this._originalaspnet_WebEvent_Events.RequestUrl;
            this._exception_type = this._originalaspnet_WebEvent_Events.ExceptionType;
            this._details = this._originalaspnet_WebEvent_Events.Details;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalaspnet_WebEvent_Events == null) return;
            this._aspnet___web_event___events.EventId = this._originalaspnet_WebEvent_Events.EventId;
            this._aspnet___web_event___events.EventTimeUtc = this._originalaspnet_WebEvent_Events.EventTimeUtc;
            this._aspnet___web_event___events.EventTime = this._originalaspnet_WebEvent_Events.EventTime;
            this._aspnet___web_event___events.EventType = this._originalaspnet_WebEvent_Events.EventType;
            this._aspnet___web_event___events.EventSequence = this._originalaspnet_WebEvent_Events.EventSequence;
            this._aspnet___web_event___events.EventOccurrence = this._originalaspnet_WebEvent_Events.EventOccurrence;
            this._aspnet___web_event___events.EventCode = this._originalaspnet_WebEvent_Events.EventCode;
            this._aspnet___web_event___events.EventDetailCode = this._originalaspnet_WebEvent_Events.EventDetailCode;
            this._aspnet___web_event___events.Message = this._originalaspnet_WebEvent_Events.Message;
            this._aspnet___web_event___events.ApplicationPath = this._originalaspnet_WebEvent_Events.ApplicationPath;
            this._aspnet___web_event___events.ApplicationVirtualPath = this._originalaspnet_WebEvent_Events.ApplicationVirtualPath;
            this._aspnet___web_event___events.MachineName = this._originalaspnet_WebEvent_Events.MachineName;
            this._aspnet___web_event___events.RequestUrl = this._originalaspnet_WebEvent_Events.RequestUrl;
            this._aspnet___web_event___events.ExceptionType = this._originalaspnet_WebEvent_Events.ExceptionType;
            this._aspnet___web_event___events.Details = this._originalaspnet_WebEvent_Events.Details;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion


        #region Primitive Properties

        
        private string _event_id;
        public string EventId
        {
            get { return this._event_id; }
            set
            {
                if (this._event_id != value)
                {
                    this.IsDirty = true;
                    this._event_id = value;
                }
            }
        }
        
        private System.DateTime _event_time_utc;
        public System.DateTime EventTimeUtc
        {
            get { return this._event_time_utc; }
            set
            {
                if (this._event_time_utc != value)
                {
                    this.IsDirty = true;
                    this._event_time_utc = value;
                }
            }
        }
        
        private System.DateTime _event_time;
        public System.DateTime EventTime
        {
            get { return this._event_time; }
            set
            {
                if (this._event_time != value)
                {
                    this.IsDirty = true;
                    this._event_time = value;
                }
            }
        }
        
        private string _event_type;
        public string EventType
        {
            get { return this._event_type; }
            set
            {
                if (this._event_type != value)
                {
                    this.IsDirty = true;
                    this._event_type = value;
                }
            }
        }
        
        private decimal _event_sequence;
        public decimal EventSequence
        {
            get { return this._event_sequence; }
            set
            {
                if (this._event_sequence != value)
                {
                    this.IsDirty = true;
                    this._event_sequence = value;
                }
            }
        }
        
        private decimal _event_occurrence;
        public decimal EventOccurrence
        {
            get { return this._event_occurrence; }
            set
            {
                if (this._event_occurrence != value)
                {
                    this.IsDirty = true;
                    this._event_occurrence = value;
                }
            }
        }
        
        private int _event_code;
        public int EventCode
        {
            get { return this._event_code; }
            set
            {
                if (this._event_code != value)
                {
                    this.IsDirty = true;
                    this._event_code = value;
                }
            }
        }
        
        private int _event_detail_code;
        public int EventDetailCode
        {
            get { return this._event_detail_code; }
            set
            {
                if (this._event_detail_code != value)
                {
                    this.IsDirty = true;
                    this._event_detail_code = value;
                }
            }
        }
        
        private string _message;
        public string Message
        {
            get { return this._message; }
            set
            {
                if (this._message != value)
                {
                    this.IsDirty = true;
                    this._message = value;
                }
            }
        }
        
        private string _application_path;
        public string ApplicationPath
        {
            get { return this._application_path; }
            set
            {
                if (this._application_path != value)
                {
                    this.IsDirty = true;
                    this._application_path = value;
                }
            }
        }
        
        private string _application_virtual_path;
        public string ApplicationVirtualPath
        {
            get { return this._application_virtual_path; }
            set
            {
                if (this._application_virtual_path != value)
                {
                    this.IsDirty = true;
                    this._application_virtual_path = value;
                }
            }
        }
        
        private string _machine_name;
        public string MachineName
        {
            get { return this._machine_name; }
            set
            {
                if (this._machine_name != value)
                {
                    this.IsDirty = true;
                    this._machine_name = value;
                }
            }
        }
        
        private string _request_url;
        public string RequestUrl
        {
            get { return this._request_url; }
            set
            {
                if (this._request_url != value)
                {
                    this.IsDirty = true;
                    this._request_url = value;
                }
            }
        }
        
        private string _exception_type;
        public string ExceptionType
        {
            get { return this._exception_type; }
            set
            {
                if (this._exception_type != value)
                {
                    this.IsDirty = true;
                    this._exception_type = value;
                }
            }
        }
        
        private string _details;
        public string Details
        {
            get { return this._details; }
            set
            {
                if (this._details != value)
                {
                    this.IsDirty = true;
                    this._details = value;
                }
            }
        }

        #endregion


        #region all the custom code


        #endregion

    }
}
