//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Models
{
    /// <summary>
    /// Model for table aspnet_Roles 
    /// </summary>
    public partial class aspnet_RolesModel 
    {
        #region Ctor

        // Default contructor
        public aspnet_RolesModel()
        {
            this.IsNewItem = true;
            this._aspnet___roles = new aspnet_Roles();
        }

        // Default contructor that set entity to field
        public aspnet_RolesModel(aspnet_Roles aspnet_roles)
        {
        	this._aspnet___roles = aspnet_roles;
            this._application_id = aspnet_roles.ApplicationId;
            this._role_id = aspnet_roles.RoleId;
            this._role_name = aspnet_roles.RoleName;
            this._lowered_role_name = aspnet_roles.LoweredRoleName;
            this._description = aspnet_roles.Description;
            this._originalaspnet_Roles = aspnet_roles.DeepClone();
        }

        #endregion


        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private aspnet_Roles _aspnet___roles;
        private aspnet_Roles _originalaspnet_Roles;
        
        public aspnet_Roles Mapaspnet_Roles()
        {
            this._aspnet___roles.ApplicationId = this._application_id;
            this._aspnet___roles.RoleId = this._role_id;
            this._aspnet___roles.RoleName = this._role_name;
            this._aspnet___roles.LoweredRoleName = this._lowered_role_name;
            this._aspnet___roles.Description = this._description;
        	return _aspnet___roles;
        }
        
        public void Undo()
        {
            if(this._originalaspnet_Roles == null) return;
            this._application_id = this._originalaspnet_Roles.ApplicationId;
            this._role_id = this._originalaspnet_Roles.RoleId;
            this._role_name = this._originalaspnet_Roles.RoleName;
            this._lowered_role_name = this._originalaspnet_Roles.LoweredRoleName;
            this._description = this._originalaspnet_Roles.Description;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalaspnet_Roles == null) return;
            this._aspnet___roles.ApplicationId = this._originalaspnet_Roles.ApplicationId;
            this._aspnet___roles.RoleId = this._originalaspnet_Roles.RoleId;
            this._aspnet___roles.RoleName = this._originalaspnet_Roles.RoleName;
            this._aspnet___roles.LoweredRoleName = this._originalaspnet_Roles.LoweredRoleName;
            this._aspnet___roles.Description = this._originalaspnet_Roles.Description;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion


        #region Primitive Properties

        
        private System.Guid _application_id;
        public System.Guid ApplicationId
        {
            get { return this._application_id; }
            set
            {
                if (this._application_id != value)
                {
                    this.IsDirty = true;
                    this._application_id = value;
                }
            }
        }
        
        private System.Guid _role_id;
        public System.Guid RoleId
        {
            get { return this._role_id; }
            set
            {
                if (this._role_id != value)
                {
                    this.IsDirty = true;
                    this._role_id = value;
                }
            }
        }
        
        private string _role_name;
        public string RoleName
        {
            get { return this._role_name; }
            set
            {
                if (this._role_name != value)
                {
                    this.IsDirty = true;
                    this._role_name = value;
                }
            }
        }
        
        private string _lowered_role_name;
        public string LoweredRoleName
        {
            get { return this._lowered_role_name; }
            set
            {
                if (this._lowered_role_name != value)
                {
                    this.IsDirty = true;
                    this._lowered_role_name = value;
                }
            }
        }
        
        private string _description;
        public string Description
        {
            get { return this._description; }
            set
            {
                if (this._description != value)
                {
                    this.IsDirty = true;
                    this._description = value;
                }
            }
        }

        #endregion


        #region all the custom code


        #endregion

    }
}
