//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Models
{
    /// <summary>
    /// Model for table aspnet_PersonalizationAllUsers 
    /// </summary>
    public partial class aspnet_PersonalizationAllUsersModel 
    {
        #region Ctor

        // Default contructor
        public aspnet_PersonalizationAllUsersModel()
        {
            this.IsNewItem = true;
            this._aspnet___personalization_all_users = new aspnet_PersonalizationAllUsers();
        }

        // Default contructor that set entity to field
        public aspnet_PersonalizationAllUsersModel(aspnet_PersonalizationAllUsers aspnet_personalizationallusers)
        {
        	this._aspnet___personalization_all_users = aspnet_personalizationallusers;
            this._path_id = aspnet_personalizationallusers.PathId;
            this._page_settings = aspnet_personalizationallusers.PageSettings;
            this._last_updated_date = aspnet_personalizationallusers.LastUpdatedDate;
            this._originalaspnet_PersonalizationAllUsers = aspnet_personalizationallusers.DeepClone();
        }

        #endregion


        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private aspnet_PersonalizationAllUsers _aspnet___personalization_all_users;
        private aspnet_PersonalizationAllUsers _originalaspnet_PersonalizationAllUsers;
        
        public aspnet_PersonalizationAllUsers Mapaspnet_PersonalizationAllUsers()
        {
            this._aspnet___personalization_all_users.PathId = this._path_id;
            this._aspnet___personalization_all_users.PageSettings = this._page_settings;
            this._aspnet___personalization_all_users.LastUpdatedDate = this._last_updated_date;
        	return _aspnet___personalization_all_users;
        }
        
        public void Undo()
        {
            if(this._originalaspnet_PersonalizationAllUsers == null) return;
            this._path_id = this._originalaspnet_PersonalizationAllUsers.PathId;
            this._page_settings = this._originalaspnet_PersonalizationAllUsers.PageSettings;
            this._last_updated_date = this._originalaspnet_PersonalizationAllUsers.LastUpdatedDate;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalaspnet_PersonalizationAllUsers == null) return;
            this._aspnet___personalization_all_users.PathId = this._originalaspnet_PersonalizationAllUsers.PathId;
            this._aspnet___personalization_all_users.PageSettings = this._originalaspnet_PersonalizationAllUsers.PageSettings;
            this._aspnet___personalization_all_users.LastUpdatedDate = this._originalaspnet_PersonalizationAllUsers.LastUpdatedDate;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion


        #region Primitive Properties

        
        private System.Guid _path_id;
        public System.Guid PathId
        {
            get { return this._path_id; }
            set
            {
                if (this._path_id != value)
                {
                    this.IsDirty = true;
                    this._path_id = value;
                }
            }
        }
        
        private byte[] _page_settings;
        public byte[] PageSettings
        {
            get { return this._page_settings; }
            set
            {
                if (this._page_settings != value)
                {
                    this.IsDirty = true;
                    this._page_settings = value;
                }
            }
        }
        
        private System.DateTime _last_updated_date;
        public System.DateTime LastUpdatedDate
        {
            get { return this._last_updated_date; }
            set
            {
                if (this._last_updated_date != value)
                {
                    this.IsDirty = true;
                    this._last_updated_date = value;
                }
            }
        }

        #endregion


        #region all the custom code


        #endregion

    }
}
