//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Models
{
    /// <summary>
    /// Model for table aspnet_Users 
    /// </summary>
    public partial class aspnet_UsersModel 
    {
        #region Ctor

        // Default contructor
        public aspnet_UsersModel()
        {
            this.IsNewItem = true;
            this._aspnet___users = new aspnet_Users();
        }

        // Default contructor that set entity to field
        public aspnet_UsersModel(aspnet_Users aspnet_users)
        {
        	this._aspnet___users = aspnet_users;
            this._application_id = aspnet_users.ApplicationId;
            this._user_id = aspnet_users.UserId;
            this._user_name = aspnet_users.UserName;
            this._lowered_user_name = aspnet_users.LoweredUserName;
            this._mobile_alias = aspnet_users.MobileAlias;
            this._is_anonymous = aspnet_users.IsAnonymous;
            this._last_activity_date = aspnet_users.LastActivityDate;
            this._originalaspnet_Users = aspnet_users.DeepClone();
        }

        #endregion


        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private aspnet_Users _aspnet___users;
        private aspnet_Users _originalaspnet_Users;
        
        public aspnet_Users Mapaspnet_Users()
        {
            this._aspnet___users.ApplicationId = this._application_id;
            this._aspnet___users.UserId = this._user_id;
            this._aspnet___users.UserName = this._user_name;
            this._aspnet___users.LoweredUserName = this._lowered_user_name;
            this._aspnet___users.MobileAlias = this._mobile_alias;
            this._aspnet___users.IsAnonymous = this._is_anonymous;
            this._aspnet___users.LastActivityDate = this._last_activity_date;
        	return _aspnet___users;
        }
        
        public void Undo()
        {
            if(this._originalaspnet_Users == null) return;
            this._application_id = this._originalaspnet_Users.ApplicationId;
            this._user_id = this._originalaspnet_Users.UserId;
            this._user_name = this._originalaspnet_Users.UserName;
            this._lowered_user_name = this._originalaspnet_Users.LoweredUserName;
            this._mobile_alias = this._originalaspnet_Users.MobileAlias;
            this._is_anonymous = this._originalaspnet_Users.IsAnonymous;
            this._last_activity_date = this._originalaspnet_Users.LastActivityDate;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalaspnet_Users == null) return;
            this._aspnet___users.ApplicationId = this._originalaspnet_Users.ApplicationId;
            this._aspnet___users.UserId = this._originalaspnet_Users.UserId;
            this._aspnet___users.UserName = this._originalaspnet_Users.UserName;
            this._aspnet___users.LoweredUserName = this._originalaspnet_Users.LoweredUserName;
            this._aspnet___users.MobileAlias = this._originalaspnet_Users.MobileAlias;
            this._aspnet___users.IsAnonymous = this._originalaspnet_Users.IsAnonymous;
            this._aspnet___users.LastActivityDate = this._originalaspnet_Users.LastActivityDate;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion


        #region Primitive Properties

        
        private System.Guid _application_id;
        public System.Guid ApplicationId
        {
            get { return this._application_id; }
            set
            {
                if (this._application_id != value)
                {
                    this.IsDirty = true;
                    this._application_id = value;
                }
            }
        }
        
        private System.Guid _user_id;
        public System.Guid UserId
        {
            get { return this._user_id; }
            set
            {
                if (this._user_id != value)
                {
                    this.IsDirty = true;
                    this._user_id = value;
                }
            }
        }
        
        private string _user_name;
        public string UserName
        {
            get { return this._user_name; }
            set
            {
                if (this._user_name != value)
                {
                    this.IsDirty = true;
                    this._user_name = value;
                }
            }
        }
        
        private string _lowered_user_name;
        public string LoweredUserName
        {
            get { return this._lowered_user_name; }
            set
            {
                if (this._lowered_user_name != value)
                {
                    this.IsDirty = true;
                    this._lowered_user_name = value;
                }
            }
        }
        
        private string _mobile_alias;
        public string MobileAlias
        {
            get { return this._mobile_alias; }
            set
            {
                if (this._mobile_alias != value)
                {
                    this.IsDirty = true;
                    this._mobile_alias = value;
                }
            }
        }
        
        private bool _is_anonymous;
        public bool IsAnonymous
        {
            get { return this._is_anonymous; }
            set
            {
                if (this._is_anonymous != value)
                {
                    this.IsDirty = true;
                    this._is_anonymous = value;
                }
            }
        }
        
        private System.DateTime _last_activity_date;
        public System.DateTime LastActivityDate
        {
            get { return this._last_activity_date; }
            set
            {
                if (this._last_activity_date != value)
                {
                    this.IsDirty = true;
                    this._last_activity_date = value;
                }
            }
        }

        #endregion


        #region all the custom code


        #endregion

    }
}
