//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Models
{
    /// <summary>
    /// Model for table aspnet_Applications 
    /// </summary>
    public partial class aspnet_ApplicationsModel 
    {
        #region Ctor

        // Default contructor
        public aspnet_ApplicationsModel()
        {
            this.IsNewItem = true;
            this._aspnet___applications = new aspnet_Applications();
        }

        // Default contructor that set entity to field
        public aspnet_ApplicationsModel(aspnet_Applications aspnet_applications)
        {
        	this._aspnet___applications = aspnet_applications;
            this._application_name = aspnet_applications.ApplicationName;
            this._lowered_application_name = aspnet_applications.LoweredApplicationName;
            this._application_id = aspnet_applications.ApplicationId;
            this._description = aspnet_applications.Description;
            this._originalaspnet_Applications = aspnet_applications.DeepClone();
        }

        #endregion


        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private aspnet_Applications _aspnet___applications;
        private aspnet_Applications _originalaspnet_Applications;
        
        public aspnet_Applications Mapaspnet_Applications()
        {
            this._aspnet___applications.ApplicationName = this._application_name;
            this._aspnet___applications.LoweredApplicationName = this._lowered_application_name;
            this._aspnet___applications.ApplicationId = this._application_id;
            this._aspnet___applications.Description = this._description;
        	return _aspnet___applications;
        }
        
        public void Undo()
        {
            if(this._originalaspnet_Applications == null) return;
            this._application_name = this._originalaspnet_Applications.ApplicationName;
            this._lowered_application_name = this._originalaspnet_Applications.LoweredApplicationName;
            this._application_id = this._originalaspnet_Applications.ApplicationId;
            this._description = this._originalaspnet_Applications.Description;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalaspnet_Applications == null) return;
            this._aspnet___applications.ApplicationName = this._originalaspnet_Applications.ApplicationName;
            this._aspnet___applications.LoweredApplicationName = this._originalaspnet_Applications.LoweredApplicationName;
            this._aspnet___applications.ApplicationId = this._originalaspnet_Applications.ApplicationId;
            this._aspnet___applications.Description = this._originalaspnet_Applications.Description;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion


        #region Primitive Properties

        
        private string _application_name;
        public string ApplicationName
        {
            get { return this._application_name; }
            set
            {
                if (this._application_name != value)
                {
                    this.IsDirty = true;
                    this._application_name = value;
                }
            }
        }
        
        private string _lowered_application_name;
        public string LoweredApplicationName
        {
            get { return this._lowered_application_name; }
            set
            {
                if (this._lowered_application_name != value)
                {
                    this.IsDirty = true;
                    this._lowered_application_name = value;
                }
            }
        }
        
        private System.Guid _application_id;
        public System.Guid ApplicationId
        {
            get { return this._application_id; }
            set
            {
                if (this._application_id != value)
                {
                    this.IsDirty = true;
                    this._application_id = value;
                }
            }
        }
        
        private string _description;
        public string Description
        {
            get { return this._description; }
            set
            {
                if (this._description != value)
                {
                    this.IsDirty = true;
                    this._description = value;
                }
            }
        }

        #endregion


        #region all the custom code


        #endregion

    }
}
