//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Models
{
    /// <summary>
    /// Model for table Attachment 
    /// </summary>
    public partial class AttachmentModel 
    {
        #region Ctor

        // Default contructor
        public AttachmentModel()
        {
            this.IsNewItem = true;
            this._attachment = new Attachment();
        }

        // Default contructor that set entity to field
        public AttachmentModel(Attachment attachment)
        {
        	this._attachment = attachment;
            this._id = attachment.Id;
            this._file_attachments_id = attachment.FileAttachmentsId;
            this._originalAttachment = attachment.DeepClone();
        }

        #endregion


        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private Attachment _attachment;
        private Attachment _originalAttachment;
        
        public Attachment MapAttachment()
        {
            this._attachment.Id = this._id;
            this._attachment.FileAttachmentsId = this._file_attachments_id;
        	return _attachment;
        }
        
        public void Undo()
        {
            if(this._originalAttachment == null) return;
            this._id = this._originalAttachment.Id;
            this._file_attachments_id = this._originalAttachment.FileAttachmentsId;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalAttachment == null) return;
            this._attachment.Id = this._originalAttachment.Id;
            this._attachment.FileAttachmentsId = this._originalAttachment.FileAttachmentsId;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion


        #region Primitive Properties

        
        private System.Guid _id;
        public System.Guid Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                }
            }
        }
        
        private int _file_attachments_id;
        public int FileAttachmentsId
        {
            get { return this._file_attachments_id; }
            set
            {
                if (this._file_attachments_id != value)
                {
                    this.IsDirty = true;
                    this._file_attachments_id = value;
                }
            }
        }

        #endregion


        #region all the custom code


        #endregion
    }
}
