//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Models
{
    /// <summary>
    /// Model for table AttachmentFile 
    /// </summary>
    public partial class AttachmentFileModel 
    {
        #region Ctor

        // Default contructor
        public AttachmentFileModel()
        {
            this.IsNewItem = true;
            this._attachment_file = new AttachmentFile();
        }

        // Default contructor that set entity to field
        public AttachmentFileModel(AttachmentFile attachmentfile)
        {
        	this._attachment_file = attachmentfile;
            this._id = attachmentfile.Id;
            this._name = attachmentfile.Name;
            this._path_file = attachmentfile.PathFile;
            this._originalAttachmentFile = attachmentfile.DeepClone();
        }

        #endregion


        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private AttachmentFile _attachment_file;
        private AttachmentFile _originalAttachmentFile;
        
        public AttachmentFile MapAttachmentFile()
        {
            this._attachment_file.Id = this._id;
            this._attachment_file.Name = this._name;
            this._attachment_file.PathFile = this._path_file;
        	return _attachment_file;
        }
        
        public void Undo()
        {
            if(this._originalAttachmentFile == null) return;
            this._id = this._originalAttachmentFile.Id;
            this._name = this._originalAttachmentFile.Name;
            this._path_file = this._originalAttachmentFile.PathFile;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalAttachmentFile == null) return;
            this._attachment_file.Id = this._originalAttachmentFile.Id;
            this._attachment_file.Name = this._originalAttachmentFile.Name;
            this._attachment_file.PathFile = this._originalAttachmentFile.PathFile;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion


        #region Primitive Properties

        
        private int _id;
        public int Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                }
            }
        }
        
        private string _name;
        public string Name
        {
            get { return this._name; }
            set
            {
                if (this._name != value)
                {
                    this.IsDirty = true;
                    this._name = value;
                }
            }
        }
        
        private string _path_file;
        public string PathFile
        {
            get { return this._path_file; }
            set
            {
                if (this._path_file != value)
                {
                    this.IsDirty = true;
                    this._path_file = value;
                }
            }
        }

        #endregion


        #region all the custom code


        #endregion
    }
}
