//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Models
{
    /// <summary>
    /// Model for table StatusToStatus 
    /// </summary>
    public partial class StatusToStatusModel 
    {
        #region Ctor

        // Default contructor
        public StatusToStatusModel()
        {
            this.IsNewItem = true;
            this._status_to_status = new StatusToStatus();
        }

        // Default contructor that set entity to field
        public StatusToStatusModel(StatusToStatus statustostatus)
        {
        	this._status_to_status = statustostatus;
            this._status_id = statustostatus.StatusId;
            this._link_to_status_id = statustostatus.LinkToStatusId;
            this._originalStatusToStatus = statustostatus.DeepClone();
        }

        #endregion


        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private StatusToStatus _status_to_status;
        private StatusToStatus _originalStatusToStatus;
        
        public StatusToStatus MapStatusToStatus()
        {
            this._status_to_status.StatusId = this._status_id;
            this._status_to_status.LinkToStatusId = this._link_to_status_id;
        	return _status_to_status;
        }
        
        public void Undo()
        {
            if(this._originalStatusToStatus == null) return;
            this._status_id = this._originalStatusToStatus.StatusId;
            this._link_to_status_id = this._originalStatusToStatus.LinkToStatusId;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalStatusToStatus == null) return;
            this._status_to_status.StatusId = this._originalStatusToStatus.StatusId;
            this._status_to_status.LinkToStatusId = this._originalStatusToStatus.LinkToStatusId;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion


        #region Primitive Properties

        
        private int _status_id;
        public int StatusId
        {
            get { return this._status_id; }
            set
            {
                if (this._status_id != value)
                {
                    this.IsDirty = true;
                    this._status_id = value;
                }
            }
        }
        
        private int _link_to_status_id;
        public int LinkToStatusId
        {
            get { return this._link_to_status_id; }
            set
            {
                if (this._link_to_status_id != value)
                {
                    this.IsDirty = true;
                    this._link_to_status_id = value;
                }
            }
        }

        #endregion


        #region all the custom code


        #endregion
    }
}
