//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Models
{
    /// <summary>
    /// Model for table StatusToStatu 
    /// </summary>
    public partial class StatusToStatuModel 
    {
        #region Ctor

        // Default contructor
        public StatusToStatuModel()
        {
            this.IsNewItem = true;
            this._status_to_statu = new StatusToStatu();
        }

        // Default contructor that set entity to field
        public StatusToStatuModel(StatusToStatu statustostatu)
        {
        	this._status_to_statu = statustostatu;
            this._status_id = statustostatu.StatusId;
            this._link_to_status_id = statustostatu.LinkToStatusId;
            this._originalStatusToStatu = statustostatu.DeepClone();
        }

        #endregion


        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private StatusToStatu _status_to_statu;
        private StatusToStatu _originalStatusToStatu;
        
        public StatusToStatu MapStatusToStatu()
        {
            this._status_to_statu.StatusId = this._status_id;
            this._status_to_statu.LinkToStatusId = this._link_to_status_id;
        	return _status_to_statu;
        }
        
        public void Undo()
        {
            if(this._originalStatusToStatu == null) return;
            this._status_id = this._originalStatusToStatu.StatusId;
            this._link_to_status_id = this._originalStatusToStatu.LinkToStatusId;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalStatusToStatu == null) return;
            this._status_to_statu.StatusId = this._originalStatusToStatu.StatusId;
            this._status_to_statu.LinkToStatusId = this._originalStatusToStatu.LinkToStatusId;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion


        #region Primitive Properties

        
        private int _status_id;
        public int StatusId
        {
            get { return this._status_id; }
            set
            {
                if (this._status_id != value)
                {
                    this.IsDirty = true;
                    this._status_id = value;
                }
            }
        }
        
        private int _link_to_status_id;
        public int LinkToStatusId
        {
            get { return this._link_to_status_id; }
            set
            {
                if (this._link_to_status_id != value)
                {
                    this.IsDirty = true;
                    this._link_to_status_id = value;
                }
            }
        }

        #endregion


        #region all the custom code


        #endregion
    }
}
