//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Models
{
    /// <summary>
    /// Model for table StatusParameter 
    /// </summary>
    public partial class StatusParameterModel 
    {
        #region Ctor

        // Default contructor
        public StatusParameterModel()
        {
            this.IsNewItem = true;
            this._status_parameter = new StatusParameter();
        }

        // Default contructor that set entity to field
        public StatusParameterModel(StatusParameter statusparameter)
        {
        	this._status_parameter = statusparameter;
            this._id = statusparameter.Id;
            this._name = statusparameter.Name;
            this._type = statusparameter.Type;
            this._originalStatusParameter = statusparameter.DeepClone();
        }

        #endregion


        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private StatusParameter _status_parameter;
        private StatusParameter _originalStatusParameter;
        
        public StatusParameter MapStatusParameter()
        {
            this._status_parameter.Id = this._id;
            this._status_parameter.Name = this._name;
            this._status_parameter.Type = this._type;
        	return _status_parameter;
        }
        
        public void Undo()
        {
            if(this._originalStatusParameter == null) return;
            this._id = this._originalStatusParameter.Id;
            this._name = this._originalStatusParameter.Name;
            this._type = this._originalStatusParameter.Type;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalStatusParameter == null) return;
            this._status_parameter.Id = this._originalStatusParameter.Id;
            this._status_parameter.Name = this._originalStatusParameter.Name;
            this._status_parameter.Type = this._originalStatusParameter.Type;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion


        #region Primitive Properties

        
        private int _id;
        public int Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                }
            }
        }
        
        private string _name;
        public string Name
        {
            get { return this._name; }
            set
            {
                if (this._name != value)
                {
                    this.IsDirty = true;
                    this._name = value;
                }
            }
        }
        
        private Nullable<int> _type;
        public Nullable<int> Type
        {
            get { return this._type; }
            set
            {
                if (this._type != value)
                {
                    this.IsDirty = true;
                    this._type = value;
                }
            }
        }

        #endregion


        #region all the custom code


        #endregion
    }
}
