//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Models
{
    /// <summary>
    /// Model for table Task 
    /// </summary>
    public partial class TaskModel 
    {
        #region Ctor

        // Default contructor
        public TaskModel()
        {
            this.IsNewItem = true;
            this._task = new Task();
        }

        // Default contructor that set entity to field
        public TaskModel(Task task)
        {
        	this._task = task;
            this._id = task.Id;
            this._title = task.Title;
            this._created_date = task.CreatedDate;
            this._created_by = task.CreatedBy;
            this._modified_date = task.ModifiedDate;
            this._modified_by = task.ModifiedBy;
            this._description = task.Description;
            this._assigned_to = task.AssignedTo;
            this._status = task.Status;
            this._estimated_or_effort = task.EstimatedOrEffort;
            this._priority = task.Priority;
            this._iteration = task.Iteration;
            this._block = task.Block;
            this._area = task.Area;
            this._task_id = task.TaskId;
            this._type = task.Type;
            this._originalTask = task.DeepClone();
        }

        #endregion


        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private Task _task;
        private Task _originalTask;
        
        public Task MapTask()
        {
            this._task.Id = this._id;
            this._task.Title = this._title;
            this._task.CreatedDate = this._created_date;
            this._task.CreatedBy = this._created_by;
            this._task.ModifiedDate = this._modified_date;
            this._task.ModifiedBy = this._modified_by;
            this._task.Description = this._description;
            this._task.AssignedTo = this._assigned_to;
            this._task.Status = this._status;
            this._task.EstimatedOrEffort = this._estimated_or_effort;
            this._task.Priority = this._priority;
            this._task.Iteration = this._iteration;
            this._task.Block = this._block;
            this._task.Area = this._area;
            this._task.TaskId = this._task_id;
            this._task.Type = this._type;
        	return _task;
        }
        
        public void Undo()
        {
            if(this._originalTask == null) return;
            this._id = this._originalTask.Id;
            this._title = this._originalTask.Title;
            this._created_date = this._originalTask.CreatedDate;
            this._created_by = this._originalTask.CreatedBy;
            this._modified_date = this._originalTask.ModifiedDate;
            this._modified_by = this._originalTask.ModifiedBy;
            this._description = this._originalTask.Description;
            this._assigned_to = this._originalTask.AssignedTo;
            this._status = this._originalTask.Status;
            this._estimated_or_effort = this._originalTask.EstimatedOrEffort;
            this._priority = this._originalTask.Priority;
            this._iteration = this._originalTask.Iteration;
            this._block = this._originalTask.Block;
            this._area = this._originalTask.Area;
            this._task_id = this._originalTask.TaskId;
            this._type = this._originalTask.Type;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalTask == null) return;
            this._task.Id = this._originalTask.Id;
            this._task.Title = this._originalTask.Title;
            this._task.CreatedDate = this._originalTask.CreatedDate;
            this._task.CreatedBy = this._originalTask.CreatedBy;
            this._task.ModifiedDate = this._originalTask.ModifiedDate;
            this._task.ModifiedBy = this._originalTask.ModifiedBy;
            this._task.Description = this._originalTask.Description;
            this._task.AssignedTo = this._originalTask.AssignedTo;
            this._task.Status = this._originalTask.Status;
            this._task.EstimatedOrEffort = this._originalTask.EstimatedOrEffort;
            this._task.Priority = this._originalTask.Priority;
            this._task.Iteration = this._originalTask.Iteration;
            this._task.Block = this._originalTask.Block;
            this._task.Area = this._originalTask.Area;
            this._task.TaskId = this._originalTask.TaskId;
            this._task.Type = this._originalTask.Type;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion


        #region Primitive Properties

        
        private System.Guid _id;
        public System.Guid Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                }
            }
        }
        
        private string _title;
        public string Title
        {
            get { return this._title; }
            set
            {
                if (this._title != value)
                {
                    this.IsDirty = true;
                    this._title = value;
                }
            }
        }
        
        private Nullable<System.DateTime> _created_date;
        public Nullable<System.DateTime> CreatedDate
        {
            get { return this._created_date; }
            set
            {
                if (this._created_date != value)
                {
                    this.IsDirty = true;
                    this._created_date = value;
                }
            }
        }
        
        private string _created_by;
        public string CreatedBy
        {
            get { return this._created_by; }
            set
            {
                if (this._created_by != value)
                {
                    this.IsDirty = true;
                    this._created_by = value;
                }
            }
        }
        
        private Nullable<System.DateTime> _modified_date;
        public Nullable<System.DateTime> ModifiedDate
        {
            get { return this._modified_date; }
            set
            {
                if (this._modified_date != value)
                {
                    this.IsDirty = true;
                    this._modified_date = value;
                }
            }
        }
        
        private string _modified_by;
        public string ModifiedBy
        {
            get { return this._modified_by; }
            set
            {
                if (this._modified_by != value)
                {
                    this.IsDirty = true;
                    this._modified_by = value;
                }
            }
        }
        
        private string _description;
        public string Description
        {
            get { return this._description; }
            set
            {
                if (this._description != value)
                {
                    this.IsDirty = true;
                    this._description = value;
                }
            }
        }
        
        private System.Guid _assigned_to;
        public System.Guid AssignedTo
        {
            get { return this._assigned_to; }
            set
            {
                if (this._assigned_to != value)
                {
                    this.IsDirty = true;
                    this._assigned_to = value;
                }
            }
        }
        
        private int _status;
        public int Status
        {
            get { return this._status; }
            set
            {
                if (this._status != value)
                {
                    this.IsDirty = true;
                    this._status = value;
                }
            }
        }
        
        private Nullable<int> _estimated_or_effort;
        public Nullable<int> EstimatedOrEffort
        {
            get { return this._estimated_or_effort; }
            set
            {
                if (this._estimated_or_effort != value)
                {
                    this.IsDirty = true;
                    this._estimated_or_effort = value;
                }
            }
        }
        
        private Nullable<int> _priority;
        public Nullable<int> Priority
        {
            get { return this._priority; }
            set
            {
                if (this._priority != value)
                {
                    this.IsDirty = true;
                    this._priority = value;
                }
            }
        }
        
        private int _iteration;
        public int Iteration
        {
            get { return this._iteration; }
            set
            {
                if (this._iteration != value)
                {
                    this.IsDirty = true;
                    this._iteration = value;
                }
            }
        }
        
        private int _block;
        public int Block
        {
            get { return this._block; }
            set
            {
                if (this._block != value)
                {
                    this.IsDirty = true;
                    this._block = value;
                }
            }
        }
        
        private System.Guid _area;
        public System.Guid Area
        {
            get { return this._area; }
            set
            {
                if (this._area != value)
                {
                    this.IsDirty = true;
                    this._area = value;
                }
            }
        }
        
        private int _task_id;
        public int TaskId
        {
            get { return this._task_id; }
            set
            {
                if (this._task_id != value)
                {
                    this.IsDirty = true;
                    this._task_id = value;
                }
            }
        }
        
        private int _type;
        public int Type
        {
            get { return this._type; }
            set
            {
                if (this._type != value)
                {
                    this.IsDirty = true;
                    this._type = value;
                }
            }
        }

        #endregion


        #region all the custom code


        #endregion
    }
    public partial class TaskModel
    {
        public string StatusName { get; set; }

        public string UserName { get; set; }
    }
}
