//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Models
{
    /// <summary>
    /// Model for table TaskHistory 
    /// </summary>
    public partial class TaskHistoryModel 
    {
        #region Ctor

        // Default contructor
        public TaskHistoryModel()
        {
            this.IsNewItem = true;
            this._task_history = new TaskHistory();
        }

        // Default contructor that set entity to field
        public TaskHistoryModel(TaskHistory taskhistory)
        {
        	this._task_history = taskhistory;
            this._id = taskhistory.Id;
            this._user_id = taskhistory.UserId;
            this._created_date = taskhistory.CreatedDate;
            this._task_id = taskhistory.TaskId;
            this._content = taskhistory.Content;
            this._originalTaskHistory = taskhistory.DeepClone();
        }

        #endregion


        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private TaskHistory _task_history;
        private TaskHistory _originalTaskHistory;
        
        public TaskHistory MapTaskHistory()
        {
            this._task_history.Id = this._id;
            this._task_history.UserId = this._user_id;
            this._task_history.CreatedDate = this._created_date;
            this._task_history.TaskId = this._task_id;
            this._task_history.Content = this._content;
        	return _task_history;
        }
        
        public void Undo()
        {
            if(this._originalTaskHistory == null) return;
            this._id = this._originalTaskHistory.Id;
            this._user_id = this._originalTaskHistory.UserId;
            this._created_date = this._originalTaskHistory.CreatedDate;
            this._task_id = this._originalTaskHistory.TaskId;
            this._content = this._originalTaskHistory.Content;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalTaskHistory == null) return;
            this._task_history.Id = this._originalTaskHistory.Id;
            this._task_history.UserId = this._originalTaskHistory.UserId;
            this._task_history.CreatedDate = this._originalTaskHistory.CreatedDate;
            this._task_history.TaskId = this._originalTaskHistory.TaskId;
            this._task_history.Content = this._originalTaskHistory.Content;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion


        #region Primitive Properties

        
        private System.Guid _id;
        public System.Guid Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                }
            }
        }
        
        private System.Guid _user_id;
        public System.Guid UserId
        {
            get { return this._user_id; }
            set
            {
                if (this._user_id != value)
                {
                    this.IsDirty = true;
                    this._user_id = value;
                }
            }
        }
        
        private Nullable<System.DateTime> _created_date;
        public Nullable<System.DateTime> CreatedDate
        {
            get { return this._created_date; }
            set
            {
                if (this._created_date != value)
                {
                    this.IsDirty = true;
                    this._created_date = value;
                }
            }
        }
        
        private System.Guid _task_id;
        public System.Guid TaskId
        {
            get { return this._task_id; }
            set
            {
                if (this._task_id != value)
                {
                    this.IsDirty = true;
                    this._task_id = value;
                }
            }
        }
        
        private string _content;
        public string Content
        {
            get { return this._content; }
            set
            {
                if (this._content != value)
                {
                    this.IsDirty = true;
                    this._content = value;
                }
            }
        }

        #endregion


        #region all the custom code


        #endregion
    }
}
