//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Models
{
    /// <summary>
    /// Model for table Wiki 
    /// </summary>
    public partial class WikiModel 
    {
        #region Ctor

        // Default contructor
        public WikiModel()
        {
            this.IsNewItem = true;
            this._wiki = new Wiki();
        }

        // Default contructor that set entity to field
        public WikiModel(Wiki wiki)
        {
        	this._wiki = wiki;
            this._id = wiki.Id;
            this._subject = wiki.Subject;
            this._body = wiki.Body;
            this._type = wiki.Type;
            this._created_by = wiki.CreatedBy;
            this._modified_by = wiki.ModifiedBy;
            this._created_date = wiki.CreatedDate;
            this._modified_date = wiki.ModifiedDate;
            this._originalWiki = wiki.DeepClone();
        }

        #endregion


        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private Wiki _wiki;
        private Wiki _originalWiki;
        
        public Wiki MapWiki()
        {
            this._wiki.Id = this._id;
            this._wiki.Subject = this._subject;
            this._wiki.Body = this._body;
            this._wiki.Type = this._type;
            this._wiki.CreatedBy = this._created_by;
            this._wiki.ModifiedBy = this._modified_by;
            this._wiki.CreatedDate = this._created_date;
            this._wiki.ModifiedDate = this._modified_date;
        	return _wiki;
        }
        
        public void Undo()
        {
            if(this._originalWiki == null) return;
            this._id = this._originalWiki.Id;
            this._subject = this._originalWiki.Subject;
            this._body = this._originalWiki.Body;
            this._type = this._originalWiki.Type;
            this._created_by = this._originalWiki.CreatedBy;
            this._modified_by = this._originalWiki.ModifiedBy;
            this._created_date = this._originalWiki.CreatedDate;
            this._modified_date = this._originalWiki.ModifiedDate;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalWiki == null) return;
            this._wiki.Id = this._originalWiki.Id;
            this._wiki.Subject = this._originalWiki.Subject;
            this._wiki.Body = this._originalWiki.Body;
            this._wiki.Type = this._originalWiki.Type;
            this._wiki.CreatedBy = this._originalWiki.CreatedBy;
            this._wiki.ModifiedBy = this._originalWiki.ModifiedBy;
            this._wiki.CreatedDate = this._originalWiki.CreatedDate;
            this._wiki.ModifiedDate = this._originalWiki.ModifiedDate;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion


        #region Primitive Properties

        
        private System.Guid _id;
        public System.Guid Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                }
            }
        }
        
        private string _subject;
        public string Subject
        {
            get { return this._subject; }
            set
            {
                if (this._subject != value)
                {
                    this.IsDirty = true;
                    this._subject = value;
                }
            }
        }
        
        private string _body;
        public string Body
        {
            get { return this._body; }
            set
            {
                if (this._body != value)
                {
                    this.IsDirty = true;
                    this._body = value;
                }
            }
        }
        
        private Nullable<int> _type;
        public Nullable<int> Type
        {
            get { return this._type; }
            set
            {
                if (this._type != value)
                {
                    this.IsDirty = true;
                    this._type = value;
                }
            }
        }
        
        private System.Guid _created_by;
        public System.Guid CreatedBy
        {
            get { return this._created_by; }
            set
            {
                if (this._created_by != value)
                {
                    this.IsDirty = true;
                    this._created_by = value;
                }
            }
        }
        
        private System.Guid _modified_by;
        public System.Guid ModifiedBy
        {
            get { return this._modified_by; }
            set
            {
                if (this._modified_by != value)
                {
                    this.IsDirty = true;
                    this._modified_by = value;
                }
            }
        }
        
        private Nullable<System.DateTime> _created_date;
        public Nullable<System.DateTime> CreatedDate
        {
            get { return this._created_date; }
            set
            {
                if (this._created_date != value)
                {
                    this.IsDirty = true;
                    this._created_date = value;
                }
            }
        }
        
        private Nullable<System.DateTime> _modified_date;
        public Nullable<System.DateTime> ModifiedDate
        {
            get { return this._modified_date; }
            set
            {
                if (this._modified_date != value)
                {
                    this.IsDirty = true;
                    this._modified_date = value;
                }
            }
        }

        #endregion


        #region all the custom code


        #endregion

    }
}
