//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Linq.Expressions;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Repositories
{
    /// <summary>
    /// Repository for table aspnet_SchemaVersions 
    /// </summary>
    public partial class aspnet_SchemaVersionsRepository
    {
        #region auto generate code

        #region variable define

        IUnitOfWork unitOfWork;

        #endregion


        #region Ctor

        // Default contructor that creates an instance of unit of work
        public aspnet_SchemaVersionsRepository()
        {
            if (null == unitOfWork)
                unitOfWork = new UnitOfWork();
        }

        // Constructor of an instance of unit of work
        public aspnet_SchemaVersionsRepository(IUnitOfWork _unitOfWork)
        {
            unitOfWork = _unitOfWork;
        }

        #endregion


        #region Basic C.R.U.D. operations

        // List of all aspnet_SchemaVersions 
        public IList<aspnet_SchemaVersions> GetAllaspnet_SchemaVersions()
        {
            return unitOfWork.GetAll<aspnet_SchemaVersions>();
        }

        // Find all aspnet_SchemaVersions 
        public IList<aspnet_SchemaVersions> Findaspnet_SchemaVersions(Expression<Func<aspnet_SchemaVersions, bool>> expression)
        {
            return unitOfWork.Find<aspnet_SchemaVersions>(expression).ToList();
        }

        // Get single aspnet_SchemaVersions 
        public aspnet_SchemaVersions GetSingleaspnet_SchemaVersions(Func<aspnet_SchemaVersions, bool> expression)
        {
            return unitOfWork.GetSingle<aspnet_SchemaVersions>(expression);
        }

        // Add a new aspnet_SchemaVersions 
        public aspnet_SchemaVersions Addaspnet_SchemaVersions(aspnet_SchemaVersions _aspnet_SchemaVersions)
        {
            unitOfWork.Add<aspnet_SchemaVersions>(_aspnet_SchemaVersions);
            return _aspnet_SchemaVersions;
        }

        // Delete a existed aspnet_SchemaVersions 
        public void Deleteaspnet_SchemaVersions(aspnet_SchemaVersions _aspnet_SchemaVersions)
        {
            unitOfWork.Delete<aspnet_SchemaVersions>(_aspnet_SchemaVersions);
        }

        // Delete batch a existed aspnet_SchemaVersions 
        public void DeleteBatchaspnet_SchemaVersions(IEnumerable<aspnet_SchemaVersions> collection)
        {
        	foreach(var item in collection)
        	{
        		unitOfWork.Delete<aspnet_SchemaVersions>(item);
        	}
        }

        // Update a existed aspnet_SchemaVersions 
        public aspnet_SchemaVersions Updateaspnet_SchemaVersions(aspnet_SchemaVersions _aspnet_SchemaVersions)
        {
            unitOfWork.Update<aspnet_SchemaVersions>(_aspnet_SchemaVersions);
            return _aspnet_SchemaVersions;
        }

        // Refresh an existed aspnet_SchemaVersions 
        public aspnet_SchemaVersions Refeshaspnet_SchemaVersions(aspnet_SchemaVersions _aspnet_SchemaVersions)
        {
            unitOfWork.Refresh<aspnet_SchemaVersions>(_aspnet_SchemaVersions);
            return _aspnet_SchemaVersions;
        }

        // Refresh Allaspnet_SchemaVersions 
        public void RefreshListaspnet_SchemaVersions(IEnumerable<aspnet_SchemaVersions> list)
        {
            unitOfWork.RefreshList<aspnet_SchemaVersions>(list);
        }

        // Commit all changes 
        public void Commit()
        {
            unitOfWork.Commit();
        }

        #endregion


        #endregion


        #region all the custom code


        #endregion

    }
}
