//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Linq.Expressions;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Repositories
{
    /// <summary>
    /// Repository for table aspnet_WebEvent_Events 
    /// </summary>
    public partial class aspnet_WebEvent_EventsRepository
    {
        #region auto generate code

        #region variable define

        IUnitOfWork unitOfWork;

        #endregion


        #region Ctor

        // Default contructor that creates an instance of unit of work
        public aspnet_WebEvent_EventsRepository()
        {
            if (null == unitOfWork)
                unitOfWork = new UnitOfWork();
        }

        // Constructor of an instance of unit of work
        public aspnet_WebEvent_EventsRepository(IUnitOfWork _unitOfWork)
        {
            unitOfWork = _unitOfWork;
        }

        #endregion


        #region Basic C.R.U.D. operations

        // List of all aspnet_WebEvent_Events 
        public IList<aspnet_WebEvent_Events> GetAllaspnet_WebEvent_Events()
        {
            return unitOfWork.GetAll<aspnet_WebEvent_Events>();
        }

        // Find all aspnet_WebEvent_Events 
        public IList<aspnet_WebEvent_Events> Findaspnet_WebEvent_Events(Expression<Func<aspnet_WebEvent_Events, bool>> expression)
        {
            return unitOfWork.Find<aspnet_WebEvent_Events>(expression).ToList();
        }

        // Get single aspnet_WebEvent_Events 
        public aspnet_WebEvent_Events GetSingleaspnet_WebEvent_Events(Func<aspnet_WebEvent_Events, bool> expression)
        {
            return unitOfWork.GetSingle<aspnet_WebEvent_Events>(expression);
        }

        // Add a new aspnet_WebEvent_Events 
        public aspnet_WebEvent_Events Addaspnet_WebEvent_Events(aspnet_WebEvent_Events _aspnet_WebEvent_Events)
        {
            unitOfWork.Add<aspnet_WebEvent_Events>(_aspnet_WebEvent_Events);
            return _aspnet_WebEvent_Events;
        }

        // Delete a existed aspnet_WebEvent_Events 
        public void Deleteaspnet_WebEvent_Events(aspnet_WebEvent_Events _aspnet_WebEvent_Events)
        {
            unitOfWork.Delete<aspnet_WebEvent_Events>(_aspnet_WebEvent_Events);
        }

        // Delete batch a existed aspnet_WebEvent_Events 
        public void DeleteBatchaspnet_WebEvent_Events(IEnumerable<aspnet_WebEvent_Events> collection)
        {
        	foreach(var item in collection)
        	{
        		unitOfWork.Delete<aspnet_WebEvent_Events>(item);
        	}
        }

        // Update a existed aspnet_WebEvent_Events 
        public aspnet_WebEvent_Events Updateaspnet_WebEvent_Events(aspnet_WebEvent_Events _aspnet_WebEvent_Events)
        {
            unitOfWork.Update<aspnet_WebEvent_Events>(_aspnet_WebEvent_Events);
            return _aspnet_WebEvent_Events;
        }

        // Refresh an existed aspnet_WebEvent_Events 
        public aspnet_WebEvent_Events Refeshaspnet_WebEvent_Events(aspnet_WebEvent_Events _aspnet_WebEvent_Events)
        {
            unitOfWork.Refresh<aspnet_WebEvent_Events>(_aspnet_WebEvent_Events);
            return _aspnet_WebEvent_Events;
        }

        // Refresh Allaspnet_WebEvent_Events 
        public void RefreshListaspnet_WebEvent_Events(IEnumerable<aspnet_WebEvent_Events> list)
        {
            unitOfWork.RefreshList<aspnet_WebEvent_Events>(list);
        }

        // Commit all changes 
        public void Commit()
        {
            unitOfWork.Commit();
        }

        #endregion


        #endregion


        #region all the custom code


        #endregion

    }
}
