//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Linq.Expressions;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Repositories
{
    /// <summary>
    /// Repository for table aspnet_PersonalizationPerUser 
    /// </summary>
    public partial class aspnet_PersonalizationPerUserRepository
    {
        #region auto generate code

        #region variable define

        IUnitOfWork unitOfWork;

        #endregion


        #region Ctor

        // Default contructor that creates an instance of unit of work
        public aspnet_PersonalizationPerUserRepository()
        {
            if (null == unitOfWork)
                unitOfWork = new UnitOfWork();
        }

        // Constructor of an instance of unit of work
        public aspnet_PersonalizationPerUserRepository(IUnitOfWork _unitOfWork)
        {
            unitOfWork = _unitOfWork;
        }

        #endregion


        #region Basic C.R.U.D. operations

        // List of all aspnet_PersonalizationPerUser 
        public IList<aspnet_PersonalizationPerUser> GetAllaspnet_PersonalizationPerUser()
        {
            return unitOfWork.GetAll<aspnet_PersonalizationPerUser>();
        }

        // Find all aspnet_PersonalizationPerUser 
        public IList<aspnet_PersonalizationPerUser> Findaspnet_PersonalizationPerUser(Expression<Func<aspnet_PersonalizationPerUser, bool>> expression)
        {
            return unitOfWork.Find<aspnet_PersonalizationPerUser>(expression).ToList();
        }

        // Get single aspnet_PersonalizationPerUser 
        public aspnet_PersonalizationPerUser GetSingleaspnet_PersonalizationPerUser(Func<aspnet_PersonalizationPerUser, bool> expression)
        {
            return unitOfWork.GetSingle<aspnet_PersonalizationPerUser>(expression);
        }

        // Add a new aspnet_PersonalizationPerUser 
        public aspnet_PersonalizationPerUser Addaspnet_PersonalizationPerUser(aspnet_PersonalizationPerUser _aspnet_PersonalizationPerUser)
        {
            unitOfWork.Add<aspnet_PersonalizationPerUser>(_aspnet_PersonalizationPerUser);
            return _aspnet_PersonalizationPerUser;
        }

        // Delete a existed aspnet_PersonalizationPerUser 
        public void Deleteaspnet_PersonalizationPerUser(aspnet_PersonalizationPerUser _aspnet_PersonalizationPerUser)
        {
            unitOfWork.Delete<aspnet_PersonalizationPerUser>(_aspnet_PersonalizationPerUser);
        }

        // Delete batch a existed aspnet_PersonalizationPerUser 
        public void DeleteBatchaspnet_PersonalizationPerUser(IEnumerable<aspnet_PersonalizationPerUser> collection)
        {
        	foreach(var item in collection)
        	{
        		unitOfWork.Delete<aspnet_PersonalizationPerUser>(item);
        	}
        }

        // Update a existed aspnet_PersonalizationPerUser 
        public aspnet_PersonalizationPerUser Updateaspnet_PersonalizationPerUser(aspnet_PersonalizationPerUser _aspnet_PersonalizationPerUser)
        {
            unitOfWork.Update<aspnet_PersonalizationPerUser>(_aspnet_PersonalizationPerUser);
            return _aspnet_PersonalizationPerUser;
        }

        // Refresh an existed aspnet_PersonalizationPerUser 
        public aspnet_PersonalizationPerUser Refeshaspnet_PersonalizationPerUser(aspnet_PersonalizationPerUser _aspnet_PersonalizationPerUser)
        {
            unitOfWork.Refresh<aspnet_PersonalizationPerUser>(_aspnet_PersonalizationPerUser);
            return _aspnet_PersonalizationPerUser;
        }

        // Refresh Allaspnet_PersonalizationPerUser 
        public void RefreshListaspnet_PersonalizationPerUser(IEnumerable<aspnet_PersonalizationPerUser> list)
        {
            unitOfWork.RefreshList<aspnet_PersonalizationPerUser>(list);
        }

        // Commit all changes 
        public void Commit()
        {
            unitOfWork.Commit();
        }

        #endregion


        #endregion


        #region all the custom code


        #endregion

    }
}
