//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Linq.Expressions;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Repositories
{
    /// <summary>
    /// Repository for table aspnet_Profile 
    /// </summary>
    public partial class aspnet_ProfileRepository
    {
        #region auto generate code

        #region variable define

        IUnitOfWork unitOfWork;

        #endregion


        #region Ctor

        // Default contructor that creates an instance of unit of work
        public aspnet_ProfileRepository()
        {
            if (null == unitOfWork)
                unitOfWork = new UnitOfWork();
        }

        // Constructor of an instance of unit of work
        public aspnet_ProfileRepository(IUnitOfWork _unitOfWork)
        {
            unitOfWork = _unitOfWork;
        }

        #endregion


        #region Basic C.R.U.D. operations

        // List of all aspnet_Profile 
        public IList<aspnet_Profile> GetAllaspnet_Profile()
        {
            return unitOfWork.GetAll<aspnet_Profile>();
        }

        // Find all aspnet_Profile 
        public IList<aspnet_Profile> Findaspnet_Profile(Expression<Func<aspnet_Profile, bool>> expression)
        {
            return unitOfWork.Find<aspnet_Profile>(expression).ToList();
        }

        // Get single aspnet_Profile 
        public aspnet_Profile GetSingleaspnet_Profile(Func<aspnet_Profile, bool> expression)
        {
            return unitOfWork.GetSingle<aspnet_Profile>(expression);
        }

        // Add a new aspnet_Profile 
        public aspnet_Profile Addaspnet_Profile(aspnet_Profile _aspnet_Profile)
        {
            unitOfWork.Add<aspnet_Profile>(_aspnet_Profile);
            return _aspnet_Profile;
        }

        // Delete a existed aspnet_Profile 
        public void Deleteaspnet_Profile(aspnet_Profile _aspnet_Profile)
        {
            unitOfWork.Delete<aspnet_Profile>(_aspnet_Profile);
        }

        // Delete batch a existed aspnet_Profile 
        public void DeleteBatchaspnet_Profile(IEnumerable<aspnet_Profile> collection)
        {
        	foreach(var item in collection)
        	{
        		unitOfWork.Delete<aspnet_Profile>(item);
        	}
        }

        // Update a existed aspnet_Profile 
        public aspnet_Profile Updateaspnet_Profile(aspnet_Profile _aspnet_Profile)
        {
            unitOfWork.Update<aspnet_Profile>(_aspnet_Profile);
            return _aspnet_Profile;
        }

        // Refresh an existed aspnet_Profile 
        public aspnet_Profile Refeshaspnet_Profile(aspnet_Profile _aspnet_Profile)
        {
            unitOfWork.Refresh<aspnet_Profile>(_aspnet_Profile);
            return _aspnet_Profile;
        }

        // Refresh Allaspnet_Profile 
        public void RefreshListaspnet_Profile(IEnumerable<aspnet_Profile> list)
        {
            unitOfWork.RefreshList<aspnet_Profile>(list);
        }

        // Commit all changes 
        public void Commit()
        {
            unitOfWork.Commit();
        }

        #endregion


        #endregion


        #region all the custom code


        #endregion

    }
}
