//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Linq.Expressions;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Repositories
{
    /// <summary>
    /// Repository for table aspnet_Users 
    /// </summary>
    public partial class aspnet_UsersRepository
    {
        #region auto generate code

        #region variable define

        IUnitOfWork unitOfWork;

        #endregion


        #region Ctor

        // Default contructor that creates an instance of unit of work
        public aspnet_UsersRepository()
        {
            if (null == unitOfWork)
                unitOfWork = new UnitOfWork();
        }

        // Constructor of an instance of unit of work
        public aspnet_UsersRepository(IUnitOfWork _unitOfWork)
        {
            unitOfWork = _unitOfWork;
        }

        #endregion


        #region Basic C.R.U.D. operations

        // List of all aspnet_Users 
        public IList<aspnet_Users> GetAllaspnet_Users()
        {
            return unitOfWork.GetAll<aspnet_Users>();
        }

        // Find all aspnet_Users 
        public IList<aspnet_Users> Findaspnet_Users(Expression<Func<aspnet_Users, bool>> expression)
        {
            return unitOfWork.Find<aspnet_Users>(expression).ToList();
        }

        // Get single aspnet_Users 
        public aspnet_Users GetSingleaspnet_Users(Func<aspnet_Users, bool> expression)
        {
            return unitOfWork.GetSingle<aspnet_Users>(expression);
        }

        // Add a new aspnet_Users 
        public aspnet_Users Addaspnet_Users(aspnet_Users _aspnet_Users)
        {
            unitOfWork.Add<aspnet_Users>(_aspnet_Users);
            return _aspnet_Users;
        }

        // Delete a existed aspnet_Users 
        public void Deleteaspnet_Users(aspnet_Users _aspnet_Users)
        {
            unitOfWork.Delete<aspnet_Users>(_aspnet_Users);
        }

        // Delete batch a existed aspnet_Users 
        public void DeleteBatchaspnet_Users(IEnumerable<aspnet_Users> collection)
        {
        	foreach(var item in collection)
        	{
        		unitOfWork.Delete<aspnet_Users>(item);
        	}
        }

        // Update a existed aspnet_Users 
        public aspnet_Users Updateaspnet_Users(aspnet_Users _aspnet_Users)
        {
            unitOfWork.Update<aspnet_Users>(_aspnet_Users);
            return _aspnet_Users;
        }

        // Refresh an existed aspnet_Users 
        public aspnet_Users Refeshaspnet_Users(aspnet_Users _aspnet_Users)
        {
            unitOfWork.Refresh<aspnet_Users>(_aspnet_Users);
            return _aspnet_Users;
        }

        // Refresh Allaspnet_Users 
        public void RefreshListaspnet_Users(IEnumerable<aspnet_Users> list)
        {
            unitOfWork.RefreshList<aspnet_Users>(list);
        }

        // Commit all changes 
        public void Commit()
        {
            unitOfWork.Commit();
        }

        #endregion


        #endregion


        #region all the custom code


        #endregion

    }
}
