//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Linq.Expressions;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Repositories
{
    /// <summary>
    /// Repository for table AttachmentFile 
    /// </summary>
    public partial class AttachmentFileRepository
    {
        #region auto generate code

        #region variable define

        IUnitOfWork unitOfWork;

        #endregion


        #region Ctor

        // Default contructor that creates an instance of unit of work
        public AttachmentFileRepository()
        {
            if (null == unitOfWork)
                unitOfWork = new UnitOfWork();
        }

        // Constructor of an instance of unit of work
        public AttachmentFileRepository(IUnitOfWork _unitOfWork)
        {
            unitOfWork = _unitOfWork;
        }

        #endregion


        #region Basic C.R.U.D. operations

        // List of all AttachmentFile 
        public IList<AttachmentFile> GetAllAttachmentFile()
        {
            return unitOfWork.GetAll<AttachmentFile>();
        }

        // Find all AttachmentFile 
        public IList<AttachmentFile> FindAttachmentFile(Expression<Func<AttachmentFile, bool>> expression)
        {
            return unitOfWork.Find<AttachmentFile>(expression).ToList();
        }

        // Get single AttachmentFile 
        public AttachmentFile GetSingleAttachmentFile(Func<AttachmentFile, bool> expression)
        {
            return unitOfWork.GetSingle<AttachmentFile>(expression);
        }

        // Add a new AttachmentFile 
        public AttachmentFile AddAttachmentFile(AttachmentFile _attachmentFile)
        {
            unitOfWork.Add<AttachmentFile>(_attachmentFile);
            return _attachmentFile;
        }

        // Delete a existed AttachmentFile 
        public void DeleteAttachmentFile(AttachmentFile _attachmentFile)
        {
            unitOfWork.Delete<AttachmentFile>(_attachmentFile);
        }

        // Delete batch a existed AttachmentFile 
        public void DeleteBatchAttachmentFile(IEnumerable<AttachmentFile> collection)
        {
        	foreach(var item in collection)
        	{
        		unitOfWork.Delete<AttachmentFile>(item);
        	}
        }

        // Update a existed AttachmentFile 
        public AttachmentFile UpdateAttachmentFile(AttachmentFile _attachmentFile)
        {
            unitOfWork.Update<AttachmentFile>(_attachmentFile);
            return _attachmentFile;
        }

        // Refresh an existed AttachmentFile 
        public AttachmentFile RefeshAttachmentFile(AttachmentFile _attachmentFile)
        {
            unitOfWork.Refresh<AttachmentFile>(_attachmentFile);
            return _attachmentFile;
        }

        // Refresh AllAttachmentFile 
        public void RefreshListAttachmentFile(IEnumerable<AttachmentFile> list)
        {
            unitOfWork.RefreshList<AttachmentFile>(list);
        }

        // Commit all changes 
        public void Commit()
        {
            unitOfWork.Commit();
        }

        #endregion


        #endregion


        #region all the custom code


        #endregion
    }
}
