//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Linq.Expressions;
using VirtualTFS.DAL;

namespace VirtualTFS.DAL.Repositories
{
    /// <summary>
    /// Repository for table StatusToStatus 
    /// </summary>
    public partial class StatusToStatusRepository
    {
        #region auto generate code

        #region variable define

        IUnitOfWork unitOfWork;

        #endregion


        #region Ctor

        // Default contructor that creates an instance of unit of work
        public StatusToStatusRepository()
        {
            if (null == unitOfWork)
                unitOfWork = new UnitOfWork();
        }

        // Constructor of an instance of unit of work
        public StatusToStatusRepository(IUnitOfWork _unitOfWork)
        {
            unitOfWork = _unitOfWork;
        }

        #endregion


        #region Basic C.R.U.D. operations

        // List of all StatusToStatus 
        public IList<StatusToStatus> GetAllStatusToStatus()
        {
            return unitOfWork.GetAll<StatusToStatus>();
        }

        // Find all StatusToStatus 
        public IList<StatusToStatus> FindStatusToStatus(Expression<Func<StatusToStatus, bool>> expression)
        {
            return unitOfWork.Find<StatusToStatus>(expression).ToList();
        }

        // Get single StatusToStatus 
        public StatusToStatus GetSingleStatusToStatus(Func<StatusToStatus, bool> expression)
        {
            return unitOfWork.GetSingle<StatusToStatus>(expression);
        }

        // Add a new StatusToStatus 
        public StatusToStatus AddStatusToStatus(StatusToStatus _statusToStatus)
        {
            unitOfWork.Add<StatusToStatus>(_statusToStatus);
            return _statusToStatus;
        }

        // Delete a existed StatusToStatus 
        public void DeleteStatusToStatus(StatusToStatus _statusToStatus)
        {
            unitOfWork.Delete<StatusToStatus>(_statusToStatus);
        }

        // Delete batch a existed StatusToStatus 
        public void DeleteBatchStatusToStatus(IEnumerable<StatusToStatus> collection)
        {
        	foreach(var item in collection)
        	{
        		unitOfWork.Delete<StatusToStatus>(item);
        	}
        }

        // Update a existed StatusToStatus 
        public StatusToStatus UpdateStatusToStatus(StatusToStatus _statusToStatus)
        {
            unitOfWork.Update<StatusToStatus>(_statusToStatus);
            return _statusToStatus;
        }

        // Refresh an existed StatusToStatus 
        public StatusToStatus RefeshStatusToStatus(StatusToStatus _statusToStatus)
        {
            unitOfWork.Refresh<StatusToStatus>(_statusToStatus);
            return _statusToStatus;
        }

        // Refresh AllStatusToStatus 
        public void RefreshListStatusToStatus(IEnumerable<StatusToStatus> list)
        {
            unitOfWork.RefreshList<StatusToStatus>(list);
        }

        // Commit all changes 
        public void Commit()
        {
            unitOfWork.Commit();
        }

        #endregion


        #endregion


        #region all the custom code


        #endregion
    }
}
